name: Python Code Formatting Checks

on: ["push", "pull_request"]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.12 and PDM
        uses: pdm-project/setup-pdm@v3
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          pdm install
      - name: Run isort check
        run: |
          pdm run isort . --check --diff
      - name: Run black check
        run: |
          pdm run black . --check --diff
      - name: Run pyright check
        run: |
          pdm run npx pyright
